<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="group" nsURI="http://com.sii/group/1.0" nsPrefix="group">
  <eClassifiers xsi:type="ecore:EClass" name="Group">
    <eStructuralFeatures xsi:type="ecore:EReference" name="musiciens" upperBound="-1"
        eType="#//Musiciens" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="album" upperBound="-1"
        eType="#//Album" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tournee" lowerBound="1"
        eType="#//Tournee" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="logo" lowerBound="1" eType="#//Image"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Musiciens">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pseudonyme" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instrument" lowerBound="1"
        eType="#//MusicienInstrument"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Album">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="titre" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visuel" lowerBound="1"
        eType="#//Image" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tournee">
    <eStructuralFeatures xsi:type="ecore:EReference" name="date" upperBound="-1" eType="#//Date"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startDate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endDate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Date">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="salleName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ville" lowerBound="1" eType="#//Ville"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="salleAdresse" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Image" instanceTypeName="Image"/>
  <eClassifiers xsi:type="ecore:EEnum" name="MusicienInstrument" instanceTypeName="1- Guitare">
    <eLiterals name="Guitare" literal="MUSICIENINSTRUMENT_0"/>
    <eLiterals name="Batterie" value="1" literal="MUSICIENTINSTRUMENT_1"/>
    <eLiterals name="Basse" value="2" literal="MUSICIENINSTRUMENT_2"/>
    <eLiterals name="Micro" value="3" literal="MUSICIENINSTRUMENT_3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ville">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pays" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
